export const universalWords = [
  "ABRAZO",
  "AGUA",
  "AHORA",
  "AMISTAD",
  "AMOR",
  "AUSENCIA",
  "BELLEZA",
  "BONDAD",
  "CAMINO",
  "CASA",
  "CIELO",
  "COMPASIÓN",
  "CONCIENCIA",
  "CUIDADO",
  "CUERPO",
  "DIGNIDAD",
  "DOLOR",
  "ESCUCHA",
  "ESPERANZA",
  "FAMILIA",
  "FRAGILIDAD",
  "FRATERNIDAD",
  "FRONTERA",
  "FUEGO",
  "FUTURO",
  "GRACIAS",
  "HAMBRE",
  "HOGAR",
  "HUMANIDAD",
  "INFANCIA",
  "JUSTICIA",
  "LIBERTAD",
  "LUZ",
  "MADRE",
  "MAR",
  "MEMORIA",
  "MIEDO",
  "MIRADA",
  "NOSOTROS",
  "OTRO",
  "PADRE",
  "PAZ",
  "PERDÓN",
  "PRESENCIA",
  "PUEBLO",
  "RAÍZ",
  "REGRESO",
  "RESPETO",
  "RESPIRA",
  "RÍO",
  "SILENCIO",
  "TIEMPO",
  "TIERRA",
  "TODAVÍA",
  "TERNURA",
  "VERDAD",
  "VIDA",
  "VULNERABILIDAD",
  "VOZ",
  "ALGUIEN",
  "RECUERDA",
  "ESPERA",
  "QUÉDATE",
  "MIRA",
  "ESCUCHA",
  "COMPARTE",
  "VUELVE",
  "CUIDA",
  "PREGUNTA",
  "IMAGINA",
  "SIENTE",
  "DUDA",
  "APRENDE",
  "PERMANECE",
  "DESPIERTA",
  "NOMBRE",
  "MANOS",
  "PAN",
  "BOSQUE",
  "NOCHE",
  "MAÑANA",
  "ABUELA",
  "HIJO",
  "HIJA",
  "DESCONOCIDO",
  "REFUGIO",
  "EXILIO",
  "ORIGEN",
  "PÉRDIDA",
  "ENCUENTRO",
  "LATIDO",
  "CUÍDALO",
  "JUNTOS",
  "NADIE",
  "TODOS",
  "ALMA",
  "MEMORIA",
  "DESPEDIDA",
  "NACIMIENTO",
  "PROMESA",
  "HORIZONTE",
  "SEMILLA",
  "ÁRBOL",
  "LLUVIA",
  "PIEDRA",
  "CAMBIO",
  "CORaje".toUpperCase(),
];

export const reflections = [
  "La memoria también es una forma de presencia.",
  "La ternura también es una forma de inteligencia.",
  "Escuchar es permitir que otra existencia modifique la nuestra.",
  "Hay palabras a las que seguimos regresando.",
  "Una civilización también puede medirse por aquello que decide no destruir.",
  "Hay silencios que contienen más mundo que una respuesta.",
  "No todo lo que puede hacerse merece ser hecho.",
  "Toda esperanza necesita un lenguaje para poder existir.",
  "La dignidad comienza cuando dejamos de mirar al otro como una cosa.",
  "Hay cosas que solo existen mientras alguien las recuerda.",
  "Ningún algoritmo podrá devolverte una tarde que no viviste.",
  "No necesitas dejar una huella en el mundo. También puedes dejar el mundo un poco menos herido.",
  "La prisa puede hacer invisible aquello que más necesitábamos mirar.",
  "Una vida no necesita ser extraordinaria para ser irrepetible.",
  "Cuidar de alguien es reconocer que su fragilidad también nos concierne.",
  "Recordar no cambia el pasado, pero cambia el lugar desde donde lo miramos.",
  "Hay personas que sobreviven durante años dentro de una palabra.",
  "No conocemos el peso que puede estar cargando la persona que tenemos delante.",
  "La belleza no elimina el dolor, pero a veces permite atravesarlo.",
  "También somos aquello que decidimos no hacer.",
  "Una pregunta verdadera puede acompañarnos más tiempo que una respuesta.",
  "Nadie debería convertirse únicamente en una cifra.",
  "La indiferencia también construye el mundo.",
  "El tiempo no siempre cura; a veces simplemente enseña a convivir.",
  "Hay despedidas que empiezan mucho antes de que alguien se marche.",
  "El hogar puede ser un lugar, una persona o una memoria.",
  "Algunas heridas necesitan ser escuchadas antes de poder cerrarse.",
  "La compasión comienza cuando dejamos de preguntarnos si alguien merece nuestro cuidado.",
  "No todo silencio significa ausencia.",
  "Una palabra pronunciada a tiempo puede cambiar una noche.",
  "Quizá madurar sea comprender que casi todos estamos improvisando.",
  "La vulnerabilidad no nos aleja de lo humano: nos devuelve a ello.",
  "Toda persona lleva una historia que no cabe en su apariencia.",
  "El futuro también se construye con aquello que decidimos proteger.",
  "Hay pérdidas que nos obligan a aprender un nuevo idioma para seguir viviendo.",
  "La esperanza no siempre es luminosa. A veces simplemente consiste en continuar.",
  "Ser escuchado puede ser una de las formas más profundas de ser reconocido.",
  "Una comunidad empieza cuando el dolor del otro deja de parecernos ajeno.",
  "La memoria colectiva también está hecha de pequeños nombres.",
  "A veces regresar significa aceptar que el lugar ya no existe como lo recordábamos.",
  "No toda victoria merece celebrarse.",
  "El miedo disminuye cuando encuentra un nombre.",
  "La gratitud puede convertir lo cotidiano en acontecimiento.",
  "Hay personas que nunca sabrán cuánto significaron para nosotros.",
  "Una sociedad revela quién es en la manera en que trata a quien no puede devolverle nada.",
  "Lo que ignoramos también tiene consecuencias.",
  "La bondad rara vez hace ruido.",
  "La libertad sin responsabilidad puede convertirse en otra forma de abandono.",
  "No existe progreso humano si la dignidad queda fuera.",
  "También podemos heredar silencios.",
  "Algunas preguntas pertenecen a toda una época.",
  "Quien escucha de verdad acepta el riesgo de cambiar.",
  "El dolor del otro no necesita parecernos familiar para ser real.",
  "La infancia continúa hablando mucho después de haber terminado.",
  "Una frontera puede separar territorios sin conseguir separar recuerdos.",
  "El lenguaje puede herir, esconder, cuidar o salvar.",
  "Aquello que amamos modifica nuestra forma de mirar.",
  "Quizá vivir consista en aprender continuamente qué merece nuestra atención.",
  "Nadie recuerda todas las palabras, pero muchos recuerdan cómo los hicimos sentir.",
  "La humanidad no es una idea abstracta: siempre tiene un rostro concreto.",
  "Cada generación recibe un mundo que no eligió y entrega otro que ayudó a construir.",
  "Hay momentos en los que permanecer es una forma de valentía.",
  "Una casa vacía todavía contiene gestos.",
  "El duelo es también una forma de amor que ha perdido su lugar.",
  "La vida cotidiana está llena de despedidas que todavía no reconocemos.",
  "El conocimiento sin conciencia puede aumentar nuestra capacidad de hacer daño.",
  "Quizá la pregunta no sea cuánto podemos avanzar, sino qué estamos dejando atrás.",
  "Una persona puede necesitar ayuda mucho antes de aprender a pedirla.",
  "Todo rostro contiene algo que nunca conoceremos completamente.",
  "La compasión no exige comprenderlo todo.",
  "La memoria transforma el tiempo en territorio.",
  "La violencia empieza muchas veces cuando alguien deja de ser visto como alguien.",
  "Cuidar también significa saber detenerse.",
  "Algunas verdades necesitan tiempo antes de poder ser escuchadas.",
  "No somos independientes de aquello que destruimos.",
  "Una conversación sincera puede corregir años de distancia.",
  "El mundo también cambia en lugares donde nadie está mirando.",
  "Nada humano debería parecernos completamente ajeno.",
  "La paciencia es una forma de respeto por el tiempo del otro.",
  "Hay días en los que sobrevivir ya es una obra suficiente.",
  "Perdonar y olvidar no son la misma cosa.",
  "Una persona no debería necesitar demostrar su sufrimiento para merecer cuidado.",
  "Los recuerdos también envejecen con nosotros.",
  "Cada nombre pronunciado contra el olvido recupera una pequeña presencia.",
  "La esperanza necesita actos además de palabras.",
  "No sabemos cuántas últimas veces estamos viviendo ahora mismo.",
  "Una sociedad que ridiculiza la ternura termina empobreciéndose.",
  "Ser fuerte no debería significar dejar de sentir.",
  "Podemos aprender casi cualquier tecnología; aprender a convivir sigue siendo más difícil.",
  "La paz no es solamente ausencia de guerra.",
  "Lo que llamamos normal también debe poder ser interrogado.",
  "Alguien puede estar librando una batalla sin hacer ningún ruido.",
  "Toda decisión tecnológica es también una decisión humana.",
  "Una vida puede cambiar de dirección por una conversación inesperada.",
  "El futuro recuerda nuestras decisiones aunque nosotros no lleguemos a verlo.",
  "Hay preguntas que necesitan ser heredadas.",
  "La empatía empieza donde termina la comodidad de nuestras certezas.",
  "El planeta no es el escenario de nuestra vida: forma parte de ella.",
  "La historia también está hecha de personas que nadie escribió.",
  "El silencio puede ser refugio o abandono. Conviene aprender la diferencia.",
  "No todo lo perdido desaparece.",
  "Hay afectos que continúan trabajando en nosotros después de una despedida.",
  "La verdad puede necesitar delicadeza sin necesitar mentira.",
  "Una sociedad puede acostumbrarse a casi todo. Ese es también su peligro.",
  "La fragilidad compartida podría ser una forma de parentesco.",
  "No conocemos cuánto tiempo tenemos con las personas que amamos.",
  "La belleza merece existir aunque no produzca nada.",
  "Una palabra puede sobrevivir a quien la pronunció.",
  "El otro nunca es completamente otro.",
  "Quizá la humanidad empiece al reconocer que nadie se hizo a sí mismo.",
];

export const questions = [
  "¿A quién estás dejando desaparecer?",
  "¿Qué parte de tu vida estás aplazando?",
  "¿Sabes escuchar sin preparar una respuesta?",
  "¿Qué estás haciendo con el poco tiempo que tienes?",
  "¿Qué has normalizado que nunca debería haber sido normal?",
  "¿Qué le debes a quienes todavía no han nacido?",
  "¿Cuánta belleza has dejado de mirar por tener prisa?",
  "¿Qué defenderías aunque nadie pudiera verlo?",
  "¿En qué momento dejamos de reconocernos unos a otros?",
  "¿Qué palabra conservarías si solo pudieras salvar una?",
  "¿Qué necesita hoy el mundo para no endurecerse?",
  "¿Cuándo empieza realmente un regreso?",
  "¿A quién deberías llamar hoy?",
  "¿Qué miedo está decidiendo por ti?",
  "¿Cuándo fue la última vez que cambiaste sinceramente de opinión?",
  "¿Qué parte de tu identidad elegiste realmente?",
  "¿Qué estás dispuesto a perder para tener razón?",
  "¿Quién eres cuando nadie te está mirando?",
  "¿Cuántas veces confundimos comprender con estar de acuerdo?",
  "¿Cuánto sufrimiento tiene que existir antes de que deje de parecernos lejano?",
  "¿Qué significa para ti una vida digna?",
  "¿Quién fabrica aquello que deseas?",
  "¿Qué estás intentando demostrar y a quién?",
  "¿Qué persona recuerdas cuando escuchas la palabra casa?",
  "¿Qué recuerdo no querrías perder nunca?",
  "¿Cuánto de tu tiempo pertenece verdaderamente a tu vida?",
  "¿Sabes reconocer cuándo alguien necesita que simplemente permanezcas?",
  "¿Qué aprendiste demasiado tarde?",
  "¿Quién te enseñó a tener miedo?",
  "¿Qué harías si supieras que nadie va a recordarte?",
  "¿Qué deuda tenemos con los desconocidos?",
  "¿A quién has reducido a una etiqueta?",
  "¿Qué parte de ti necesita ser perdonada?",
  "¿Qué conversación sigues evitando?",
  "¿Puede existir progreso sin cuidado?",
  "¿Qué significa escuchar a alguien de verdad?",
  "¿Cuánto de nuestra comodidad depende del sufrimiento que no vemos?",
  "¿Qué parte del futuro estamos consumiendo hoy?",
  "¿Qué dejarías de hacer si comprendieras realmente que tu tiempo es limitado?",
  "¿Qué te impide pedir perdón?",
  "¿Qué te impide perdonar?",
  "¿Cuándo una frontera deja de ser solamente una línea?",
  "¿Quién decide qué vidas merecen convertirse en noticia?",
  "¿Por qué necesitamos convertir a alguien en enemigo?",
  "¿Qué estamos enseñando sin darnos cuenta?",
  "¿Qué recordarás de este año dentro de veinte?",
  "¿Qué permanece cuando una casa desaparece?",
  "¿Puede la memoria ser un hogar?",
  "¿Cuánto silencio necesita una pregunta?",
  "¿Cómo sería una tecnología diseñada para cuidar?",
  "¿Qué estamos perdiendo mientras intentamos ganar tiempo?",
  "¿Por qué nos cuesta tanto admitir que no sabemos?",
  "¿Qué significa ser responsable de alguien que nunca conocerás?",
  "¿Cuándo dejamos de mirar el cielo?",
  "¿Qué pequeña bondad recuerdas todavía?",
  "¿Qué habría necesitado escuchar tu yo de diez años?",
  "¿A quién estás intentando parecerte?",
  "¿Cuál fue la última cosa que hiciste sin ninguna utilidad?",
  "¿Qué vida existe detrás de la persona que acabas de cruzar?",
  "¿Por qué consideramos débiles algunas de nuestras mejores cualidades?",
  "¿Qué significa realmente pertenecer?",
  "¿Cómo se hereda una ausencia?",
  "¿De qué tenemos hambre además de comida?",
  "¿Cuánto miedo puede soportar una sociedad antes de cambiar?",
  "¿Quién cuida de quien cuida?",
  "¿Qué deberíamos negarnos a normalizar?",
  "¿Puede una máquina enseñarnos algo sobre lo que significa ser humanos?",
  "¿Qué responsabilidad acompaña al conocimiento?",
  "¿Qué parte de nuestra vida no puede convertirse en datos?",
  "¿Cómo sabremos si estamos construyendo un mundo mejor?",
  "¿Qué merece permanecer?",
  "¿Qué merece desaparecer?",
  "¿Qué estamos protegiendo cuando protegemos una lengua?",
  "¿Puede una palabra cambiar una decisión?",
  "¿Cuántas personas viven todavía dentro de tus gestos?",
  "¿Qué significa volver cuando ya no eres quien se fue?",
  "¿Por qué una historia puede hacernos sentir el dolor de alguien que nunca existió?",
  "¿Qué haces cuando nadie puede ofrecerte una respuesta?",
  "¿Qué lugar ocupa el silencio en tu vida?",
  "¿Qué sabes de la persona sentada a tu lado?",
  "¿Qué elegirías recordar al final?",
  "¿Cuál es el precio humano de nuestra velocidad?",
  "¿Qué perderíamos si dejáramos de contar historias?",
  "¿Qué sucede cuando dejamos de nombrar las cosas?",
  "¿Cuánto futuro cabe en una decisión pequeña?",
  "¿Qué significa cuidar un planeta que nunca veremos completo?",
  "¿Podemos aprender a vivir sin convertirlo todo en posesión?",
  "¿Cómo mirarán nuestras decisiones quienes todavía no han nacido?",
  "¿Qué parte de nuestra humanidad no deberíamos automatizar?",
  "¿Puede una sociedad ser rica y estar emocionalmente empobrecida?",
  "¿Cuándo fue la última vez que escuchaste sin interrumpir?",
  "¿Qué parte del mundo llevas contigo sin saberlo?",
  "¿Quién eras antes de que otros empezaran a decirte quién debías ser?",
  "¿Qué recuerdo te gustaría entregar a otra persona?",
  "¿Qué pregunta no te atreves a hacer?",
  "¿Qué estamos haciendo con nuestra capacidad de imaginar?",
  "¿Qué significa realmente estar presente?",
  "¿Quién necesita que hoy seas un poco más amable?",
  "¿Qué podemos hacer todavía?",
];

export const humanityMessages = [
  "No sois propietarios del futuro. Sois sus antepasados.",
  "Nadie debería acostumbrarse al sufrimiento de otro.",
  "Nunca había sido tan fácil estar conectados y no conocer a nadie.",
  "La tecnología amplifica nuestras capacidades. No garantiza nuestra sabiduría.",
  "Quizá el progreso consista en abandonar a menos gente por el camino.",
  "Dentro de cien años casi ninguno de nosotros estará aquí. Nuestras decisiones sí.",
  "No conviertas a nadie en una abstracción.",
  "El conocimiento humano crece. La pregunta es qué vamos a hacer con él.",
  "Una frontera existe en los mapas. El hambre existe en el cuerpo.",
  "Todavía estamos aquí.",
  "No todo problema humano necesita una solución tecnológica.",
  "Una sociedad también se define por aquello que decide proteger.",
  "No construyáis un futuro en el que la compasión sea considerada ineficiente.",
  "La velocidad no es un destino.",
  "Ningún avance compensa convertir a las personas en material descartable.",
  "La Tierra no es una herencia recibida de una sola generación.",
  "Recordad que cada estadística contiene vidas que nunca cabrán en un número.",
  "La inteligencia sin responsabilidad puede convertirse en una herramienta del daño.",
  "No llaméis inevitable a aquello que simplemente habéis decidido tolerar.",
  "El futuro no necesita espectadores.",
  "La dignidad no debería depender del lugar donde alguien nació.",
  "Una humanidad incapaz de cuidar su fragilidad será poderosa y profundamente débil.",
  "No confundáis crecimiento con dirección.",
  "Cada generación decide qué sufrimientos dejará de aceptar.",
  "No existe una tecnología neutral cuando modifica la vida de millones.",
  "No dejéis que la eficiencia sustituya todas las demás preguntas.",
  "Ninguna bandera hace menos humano al que está al otro lado.",
  "El planeta seguirá sin nosotros. La pregunta es qué mundo humano queremos dejar.",
  "La historia juzga con especial dureza aquello que una época aprendió a considerar normal.",
  "No esperéis a perder algo para reconocer su valor.",
  "El conocimiento debería aumentar también nuestra responsabilidad.",
  "Una sociedad que abandona a sus vulnerables termina abandonando una parte de sí misma.",
  "La paz exige más imaginación que la guerra.",
  "No reduzcáis a una persona al peor día de su vida.",
  "La humanidad no necesita pensar igual para reconocerse.",
  "Cuidar no debería ser una actividad secundaria de la civilización.",
  "Ningún progreso merece llamarse humano si necesita invisibilizar a quienes paga el precio.",
  "La memoria es también una defensa contra la repetición.",
  "Proteged los lugares donde todavía sea posible pensar lentamente.",
  "No permitáis que la costumbre vuelva tolerable lo intolerable.",
  "El futuro empieza mucho antes de llegar.",
  "Ningún niño debería heredar nuestros odios como si fueran patrimonio.",
  "La libertad necesita límites cuando destruye la libertad de otros.",
  "No somos únicamente consumidores del mundo.",
  "Habéis aprendido a comunicaros a través del planeta. Aprended ahora a comprenderos.",
  "La abundancia de información no garantiza conocimiento.",
  "No permitáis que aquello que puede medirse sea considerado lo único que importa.",
  "Un planeta finito no puede sostener una imaginación basada únicamente en poseer más.",
  "También existe violencia en aquello que elegimos no mirar.",
  "La convivencia será uno de los grandes desafíos tecnológicos y humanos del futuro.",
  "La naturaleza no conoce nuestras fronteras.",
  "El agua recordará nuestras decisiones.",
  "Ninguna civilización es eterna.",
  "No diseñéis máquinas para sustituir aquello que todavía no habéis aprendido a valorar.",
  "La humanidad necesitará inteligencia. Necesitará todavía más criterio.",
  "El poder de crear exige también aprender cuándo no crear.",
  "No sacrifiquéis el presente entero para construir un futuro que nadie pueda habitar.",
  "La diferencia no es una amenaza por naturaleza.",
  "Nadie elige el lugar desde el que comienza su vida.",
  "Una cultura desaparece cada vez que deja de poder contar su propia historia.",
  "La guerra empieza también en el lenguaje.",
  "Toda generación cree vivir en un momento excepcional. Todas terminan convirtiéndose en memoria.",
  "Que la tecnología aumente nuestra capacidad de cuidado, no solo nuestra capacidad de control.",
  "El mundo no necesita que todos pensemos igual. Necesita que aprendamos a no destruirnos por pensar distinto.",
  "La vulnerabilidad no es un fallo de diseño de la especie humana.",
  "La educación también consiste en aprender qué merece nuestra atención.",
  "Una sociedad sin memoria puede repetir incluso aquello que juró no repetir.",
  "No confundáis datos sobre una persona con conocer a una persona.",
  "El futuro tendrá nuestra tecnología y nuestras consecuencias.",
  "No dejéis que nadie desaparezca únicamente porque dejó de ser visible.",
  "Cada lengua contiene una forma irrepetible de mirar.",
  "La humanidad necesita espacios donde no todo tenga precio.",
  "Una pregunta ética debe acompañar a cada nueva capacidad.",
  "Ningún niño debería aprender que el odio es una obligación heredada.",
  "La dignidad no admite categorías.",
  "Una máquina puede procesar millones de voces. Escuchar sigue siendo otra cosa.",
  "El tiempo que ahorramos también debe servir para vivir.",
  "No construyáis ciudades en las que nadie pueda encontrarse.",
  "La soledad también es una cuestión colectiva.",
  "El futuro tendrá que aprender el significado de suficiente.",
  "Una especie capaz de imaginar su extinción también puede imaginar otra manera de vivir.",
  "Que el miedo no sea el arquitecto principal del futuro.",
  "No heredasteis solamente riquezas. También heredasteis responsabilidades.",
  "Cada generación debería dejar alguna crueldad definitivamente atrás.",
  "La humanidad todavía está aprendiendo a ser humanidad.",
];

export const humanGestures = [
  "Llama a alguien.",
  "Escucha.",
  "Vuelve.",
  "Pregunta su nombre.",
  "Pide perdón.",
  "Da las gracias.",
  "Mira el cielo.",
  "Quédate un poco más.",
  "No tengas tanta prisa.",
  "Abraza si puedes.",
  "Descansa.",
  "Comparte.",
  "Recuerda.",
  "Cuida.",
  "Pregunta cómo está.",
  "Apaga la pantalla un momento.",
  "Camina sin destino.",
  "Escucha una historia completa.",
  "Escribe un nombre que no quieras olvidar.",
  "Mira a alguien a los ojos.",
  "Deja hablar.",
  "No humilles.",
  "No respondas inmediatamente.",
  "Admite que no sabes.",
  "Cambia de opinión si has encontrado una razón.",
  "Di te quiero mientras todavía puedas.",
  "Come con alguien.",
  "Planta algo.",
  "Aprende el nombre de un árbol.",
  "Devuelve una llamada.",
  "Pregunta antes de juzgar.",
  "Escucha a una persona mayor.",
  "Escucha a un niño.",
  "Haz espacio.",
  "Deja algo mejor de como lo encontraste.",
  "No compartas el odio.",
  "Haz una pausa.",
  "Recuerda de dónde vienes.",
  "Protege a quien no puede protegerse.",
  "Lee despacio.",
  "Mira una fotografía antigua.",
  "Permite que alguien cambie.",
  "No conviertas un error en una identidad.",
  "Cuida tu lenguaje.",
  "Aprende a decir no.",
  "Aprende también a pedir ayuda.",
  "Pregúntate quién paga el precio.",
  "Haz algo que nadie pueda medir.",
  "Defiende algo bello.",
  "Escucha el silencio.",
  "Deja el teléfono lejos durante una conversación.",
  "No olvides comer.",
  "Duerme.",
  "Sal al exterior.",
  "Mira el agua.",
  "Respira antes de contestar.",
  "Reconoce el trabajo invisible.",
  "Agradece lo cotidiano.",
  "Pregunta qué necesita la otra persona.",
  "No supongas.",
  "Recuerda que no conoces toda la historia.",
  "Haz sitio a la duda.",
  "Protege tu capacidad de asombro.",
  "No tengas miedo de ser amable.",
  "Conserva alguna cosa inútil y hermosa.",
  "Escucha una voz distinta a la tuya.",
  "Aprende una palabra de otra lengua.",
  "Pregunta a tus mayores por su infancia.",
  "Cuenta una historia a alguien joven.",
  "No dejes que la vergüenza impida pedir ayuda.",
  "Cuida tu cuerpo.",
  "Cuida también el cuerpo del mundo.",
  "No uses la inteligencia para justificar la crueldad.",
  "No confundas ironía con profundidad.",
  "Reconoce cuando alguien tiene razón.",
  "Vuelve a leer una carta.",
  "Guarda un recuerdo.",
  "Suelta otro.",
  "Haz algo lentamente.",
  "Permanece presente.",
];

export const publicDomainQuotes = [
  {
    text: "I contain multitudes.",
    author: "Walt Whitman",
  },
  {
    text: "Hope is the thing with feathers.",
    author: "Emily Dickinson",
  },
];
